### ISSUE TITLE
Basic wifi scan not working

### ISSUE THREAD

**Issue by nicolas-f** [Seeed-Studio/Seeed_Arduino_atWiFi#3]
Hi,

I've just received Wio Terminal. I've followed the firmware update tutorial successfully:
https://wiki.seeedstudio.com/Wio-Terminal-Network-Overview/

Using this code:
https://wiki.seeedstudio.com/Wio-Terminal-Wi-Fi/#scanning-wi-fi-network-example-code

I got this output:

```

Device reset sequence finished!
Cannot initialize ESP-AT Lib!
[E][esp_event_loop.c:99] at_unified_cb(): at_unified evt: 4

[E][WiFiGeneric.cpp:477] mode(): Could not set mode! -1
[E][esp_event_loop.c:99] at_unified_cb(): at_unified evt: 4

Setup done
scan start
[E][esp_event_loop.c:99] at_unified_cb(): at_unified evt: 4

[E][esp_event_loop.c:99] at_unified_cb(): at_unified evt: 4

[E][esp_event_loop.c:99] at_unified_cb(): at_unified evt: 4

[E][WiFiGeneric.cpp:477] mode(): Could not set mode! -1
scan done
-2 networks found
```

Thx

ps: Why wifi driver code is not delivered with Wio Terminal platform ?

**Comment by ansonhex** [comment]
Hi this seems like you did not erase the initial firmware of the WiFi core on Wio Terminal properly, did you follow this: https://wiki.seeedstudio.com/Wio-Terminal-Network-Overview/#update-the-wireless-core-firmware,  did it appear to have **successfully** message at the end?

**Comment by ansonhex** [comment]
Also please feel free to move to our forum as we can respond much faster over there :D  https://forum.seeedstudio.com/c/products/wio-terminal/85

**Comment by nicolas-f** [comment]
@ansonhe97 Yes I erased the initial firmware before uploading, and I got the success message at the end. I will try under linux this time and post a message on the forum if this still not working.

best regards,

**Comment by nicolas-f** [comment]
Using ubuntu 20.04.1 it works !

```sh
./amebad_flash_tool erase --port /dev/ttyACM0
./amebad_flash_tool flash -d 20200730-rtl8720d-images-v2.2.0.2  --port /dev/ttyACM0
```

**Comment by ansonhex** [comment]
Good to hear :D seems like it did not erase properly
