### ISSUE TITLE
Missing ping() function

### ISSUE THREAD

**Issue by rei-vilo** [Seeed-Studio/Seeed_Arduino_atWiFi#4]
I would like to use the `WiFi.ping()` function described [here](https://www.arduino.cc/en/Reference/WiFi101Ping).

It seems the **Seeed_Arduino_atWiFi** library doesn't provide it. 

For IoT projects, it is very important to be able to check whether the server is alive and responding.

Do you plan to implement it?

Thank you!

**Comment by Pillar1989** [comment]
WiFi software is being refactored.Stay tuned for recent software updates.
